// Code generated by ent, DO NOT EDIT.

package synset

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/allof-dev/dictionary/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.Synset {
	return predicate.Synset(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.Synset {
	return predicate.Synset(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.Synset {
	return predicate.Synset(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.Synset {
	return predicate.Synset(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.Synset {
	return predicate.Synset(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.Synset {
	return predicate.Synset(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.Synset {
	return predicate.Synset(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.Synset {
	return predicate.Synset(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.Synset {
	return predicate.Synset(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.Synset {
	return predicate.Synset(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.Synset {
	return predicate.Synset(sql.FieldContainsFold(FieldID, id))
}

// PartOfSpeech applies equality check predicate on the "partOfSpeech" field. It's identical to PartOfSpeechEQ.
func PartOfSpeech(v string) predicate.Synset {
	return predicate.Synset(sql.FieldEQ(FieldPartOfSpeech, v))
}

// PartOfSpeechEQ applies the EQ predicate on the "partOfSpeech" field.
func PartOfSpeechEQ(v string) predicate.Synset {
	return predicate.Synset(sql.FieldEQ(FieldPartOfSpeech, v))
}

// PartOfSpeechNEQ applies the NEQ predicate on the "partOfSpeech" field.
func PartOfSpeechNEQ(v string) predicate.Synset {
	return predicate.Synset(sql.FieldNEQ(FieldPartOfSpeech, v))
}

// PartOfSpeechIn applies the In predicate on the "partOfSpeech" field.
func PartOfSpeechIn(vs ...string) predicate.Synset {
	return predicate.Synset(sql.FieldIn(FieldPartOfSpeech, vs...))
}

// PartOfSpeechNotIn applies the NotIn predicate on the "partOfSpeech" field.
func PartOfSpeechNotIn(vs ...string) predicate.Synset {
	return predicate.Synset(sql.FieldNotIn(FieldPartOfSpeech, vs...))
}

// PartOfSpeechGT applies the GT predicate on the "partOfSpeech" field.
func PartOfSpeechGT(v string) predicate.Synset {
	return predicate.Synset(sql.FieldGT(FieldPartOfSpeech, v))
}

// PartOfSpeechGTE applies the GTE predicate on the "partOfSpeech" field.
func PartOfSpeechGTE(v string) predicate.Synset {
	return predicate.Synset(sql.FieldGTE(FieldPartOfSpeech, v))
}

// PartOfSpeechLT applies the LT predicate on the "partOfSpeech" field.
func PartOfSpeechLT(v string) predicate.Synset {
	return predicate.Synset(sql.FieldLT(FieldPartOfSpeech, v))
}

// PartOfSpeechLTE applies the LTE predicate on the "partOfSpeech" field.
func PartOfSpeechLTE(v string) predicate.Synset {
	return predicate.Synset(sql.FieldLTE(FieldPartOfSpeech, v))
}

// PartOfSpeechContains applies the Contains predicate on the "partOfSpeech" field.
func PartOfSpeechContains(v string) predicate.Synset {
	return predicate.Synset(sql.FieldContains(FieldPartOfSpeech, v))
}

// PartOfSpeechHasPrefix applies the HasPrefix predicate on the "partOfSpeech" field.
func PartOfSpeechHasPrefix(v string) predicate.Synset {
	return predicate.Synset(sql.FieldHasPrefix(FieldPartOfSpeech, v))
}

// PartOfSpeechHasSuffix applies the HasSuffix predicate on the "partOfSpeech" field.
func PartOfSpeechHasSuffix(v string) predicate.Synset {
	return predicate.Synset(sql.FieldHasSuffix(FieldPartOfSpeech, v))
}

// PartOfSpeechEqualFold applies the EqualFold predicate on the "partOfSpeech" field.
func PartOfSpeechEqualFold(v string) predicate.Synset {
	return predicate.Synset(sql.FieldEqualFold(FieldPartOfSpeech, v))
}

// PartOfSpeechContainsFold applies the ContainsFold predicate on the "partOfSpeech" field.
func PartOfSpeechContainsFold(v string) predicate.Synset {
	return predicate.Synset(sql.FieldContainsFold(FieldPartOfSpeech, v))
}

// HasDefinitions applies the HasEdge predicate on the "definitions" edge.
func HasDefinitions() predicate.Synset {
	return predicate.Synset(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, DefinitionsTable, DefinitionsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasDefinitionsWith applies the HasEdge predicate on the "definitions" edge with a given conditions (other predicates).
func HasDefinitionsWith(preds ...predicate.Definition) predicate.Synset {
	return predicate.Synset(func(s *sql.Selector) {
		step := newDefinitionsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Synset) predicate.Synset {
	return predicate.Synset(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Synset) predicate.Synset {
	return predicate.Synset(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Synset) predicate.Synset {
	return predicate.Synset(sql.NotPredicates(p))
}
