// Code generated by ent, DO NOT EDIT.

package sense

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the sense type in the database.
	Label = "sense"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// EdgeSynset holds the string denoting the synset edge name in mutations.
	EdgeSynset = "synset"
	// EdgeLemma holds the string denoting the lemma edge name in mutations.
	EdgeLemma = "lemma"
	// EdgeRelFrom holds the string denoting the relfrom edge name in mutations.
	EdgeRelFrom = "relFrom"
	// EdgeRelTo holds the string denoting the relto edge name in mutations.
	EdgeRelTo = "relTo"
	// Table holds the table name of the sense in the database.
	Table = "senses"
	// SynsetTable is the table that holds the synset relation/edge.
	SynsetTable = "senses"
	// SynsetInverseTable is the table name for the Synset entity.
	// It exists in this package in order to avoid circular dependency with the "synset" package.
	SynsetInverseTable = "synsets"
	// SynsetColumn is the table column denoting the synset relation/edge.
	SynsetColumn = "sense_synset"
	// LemmaTable is the table that holds the lemma relation/edge.
	LemmaTable = "senses"
	// LemmaInverseTable is the table name for the Lemma entity.
	// It exists in this package in order to avoid circular dependency with the "lemma" package.
	LemmaInverseTable = "lemmas"
	// LemmaColumn is the table column denoting the lemma relation/edge.
	LemmaColumn = "sense_lemma"
	// RelFromTable is the table that holds the relFrom relation/edge.
	RelFromTable = "sense_relations"
	// RelFromInverseTable is the table name for the SenseRelation entity.
	// It exists in this package in order to avoid circular dependency with the "senserelation" package.
	RelFromInverseTable = "sense_relations"
	// RelFromColumn is the table column denoting the relFrom relation/edge.
	RelFromColumn = "sense_relation_to"
	// RelToTable is the table that holds the relTo relation/edge.
	RelToTable = "sense_relations"
	// RelToInverseTable is the table name for the SenseRelation entity.
	// It exists in this package in order to avoid circular dependency with the "senserelation" package.
	RelToInverseTable = "sense_relations"
	// RelToColumn is the table column denoting the relTo relation/edge.
	RelToColumn = "sense_relation_from"
)

// Columns holds all SQL columns for sense fields.
var Columns = []string{
	FieldID,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "senses"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"sense_synset",
	"sense_lemma",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

var (
	// IDValidator is a validator for the "id" field. It is called by the builders before save.
	IDValidator func(string) error
)

// OrderOption defines the ordering options for the Sense queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// BySynsetField orders the results by synset field.
func BySynsetField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newSynsetStep(), sql.OrderByField(field, opts...))
	}
}

// ByLemmaField orders the results by lemma field.
func ByLemmaField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newLemmaStep(), sql.OrderByField(field, opts...))
	}
}

// ByRelFromCount orders the results by relFrom count.
func ByRelFromCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newRelFromStep(), opts...)
	}
}

// ByRelFrom orders the results by relFrom terms.
func ByRelFrom(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newRelFromStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByRelToCount orders the results by relTo count.
func ByRelToCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newRelToStep(), opts...)
	}
}

// ByRelTo orders the results by relTo terms.
func ByRelTo(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newRelToStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newSynsetStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(SynsetInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, false, SynsetTable, SynsetColumn),
	)
}
func newLemmaStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(LemmaInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, false, LemmaTable, LemmaColumn),
	)
}
func newRelFromStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(RelFromInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, true, RelFromTable, RelFromColumn),
	)
}
func newRelToStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(RelToInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, true, RelToTable, RelToColumn),
	)
}
