// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/allof-dev/dictionary/ent/lemma"
	"github.com/allof-dev/dictionary/ent/predicate"
	"github.com/allof-dev/dictionary/ent/sense"
)

// LemmaQuery is the builder for querying Lemma entities.
type LemmaQuery struct {
	config
	ctx        *QueryContext
	order      []lemma.OrderOption
	inters     []Interceptor
	predicates []predicate.Lemma
	withSenses *SenseQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the LemmaQuery builder.
func (lq *LemmaQuery) Where(ps ...predicate.Lemma) *LemmaQuery {
	lq.predicates = append(lq.predicates, ps...)
	return lq
}

// Limit the number of records to be returned by this query.
func (lq *LemmaQuery) Limit(limit int) *LemmaQuery {
	lq.ctx.Limit = &limit
	return lq
}

// Offset to start from.
func (lq *LemmaQuery) Offset(offset int) *LemmaQuery {
	lq.ctx.Offset = &offset
	return lq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (lq *LemmaQuery) Unique(unique bool) *LemmaQuery {
	lq.ctx.Unique = &unique
	return lq
}

// Order specifies how the records should be ordered.
func (lq *LemmaQuery) Order(o ...lemma.OrderOption) *LemmaQuery {
	lq.order = append(lq.order, o...)
	return lq
}

// QuerySenses chains the current query on the "senses" edge.
func (lq *LemmaQuery) QuerySenses() *SenseQuery {
	query := (&SenseClient{config: lq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := lq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := lq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(lemma.Table, lemma.FieldID, selector),
			sqlgraph.To(sense.Table, sense.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, true, lemma.SensesTable, lemma.SensesColumn),
		)
		fromU = sqlgraph.SetNeighbors(lq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first Lemma entity from the query.
// Returns a *NotFoundError when no Lemma was found.
func (lq *LemmaQuery) First(ctx context.Context) (*Lemma, error) {
	nodes, err := lq.Limit(1).All(setContextOp(ctx, lq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{lemma.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (lq *LemmaQuery) FirstX(ctx context.Context) *Lemma {
	node, err := lq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first Lemma ID from the query.
// Returns a *NotFoundError when no Lemma ID was found.
func (lq *LemmaQuery) FirstID(ctx context.Context) (id string, err error) {
	var ids []string
	if ids, err = lq.Limit(1).IDs(setContextOp(ctx, lq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{lemma.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (lq *LemmaQuery) FirstIDX(ctx context.Context) string {
	id, err := lq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single Lemma entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one Lemma entity is found.
// Returns a *NotFoundError when no Lemma entities are found.
func (lq *LemmaQuery) Only(ctx context.Context) (*Lemma, error) {
	nodes, err := lq.Limit(2).All(setContextOp(ctx, lq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{lemma.Label}
	default:
		return nil, &NotSingularError{lemma.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (lq *LemmaQuery) OnlyX(ctx context.Context) *Lemma {
	node, err := lq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only Lemma ID in the query.
// Returns a *NotSingularError when more than one Lemma ID is found.
// Returns a *NotFoundError when no entities are found.
func (lq *LemmaQuery) OnlyID(ctx context.Context) (id string, err error) {
	var ids []string
	if ids, err = lq.Limit(2).IDs(setContextOp(ctx, lq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{lemma.Label}
	default:
		err = &NotSingularError{lemma.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (lq *LemmaQuery) OnlyIDX(ctx context.Context) string {
	id, err := lq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of Lemmas.
func (lq *LemmaQuery) All(ctx context.Context) ([]*Lemma, error) {
	ctx = setContextOp(ctx, lq.ctx, ent.OpQueryAll)
	if err := lq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*Lemma, *LemmaQuery]()
	return withInterceptors[[]*Lemma](ctx, lq, qr, lq.inters)
}

// AllX is like All, but panics if an error occurs.
func (lq *LemmaQuery) AllX(ctx context.Context) []*Lemma {
	nodes, err := lq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of Lemma IDs.
func (lq *LemmaQuery) IDs(ctx context.Context) (ids []string, err error) {
	if lq.ctx.Unique == nil && lq.path != nil {
		lq.Unique(true)
	}
	ctx = setContextOp(ctx, lq.ctx, ent.OpQueryIDs)
	if err = lq.Select(lemma.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (lq *LemmaQuery) IDsX(ctx context.Context) []string {
	ids, err := lq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (lq *LemmaQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, lq.ctx, ent.OpQueryCount)
	if err := lq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, lq, querierCount[*LemmaQuery](), lq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (lq *LemmaQuery) CountX(ctx context.Context) int {
	count, err := lq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (lq *LemmaQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, lq.ctx, ent.OpQueryExist)
	switch _, err := lq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (lq *LemmaQuery) ExistX(ctx context.Context) bool {
	exist, err := lq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the LemmaQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (lq *LemmaQuery) Clone() *LemmaQuery {
	if lq == nil {
		return nil
	}
	return &LemmaQuery{
		config:     lq.config,
		ctx:        lq.ctx.Clone(),
		order:      append([]lemma.OrderOption{}, lq.order...),
		inters:     append([]Interceptor{}, lq.inters...),
		predicates: append([]predicate.Lemma{}, lq.predicates...),
		withSenses: lq.withSenses.Clone(),
		// clone intermediate query.
		sql:  lq.sql.Clone(),
		path: lq.path,
	}
}

// WithSenses tells the query-builder to eager-load the nodes that are connected to
// the "senses" edge. The optional arguments are used to configure the query builder of the edge.
func (lq *LemmaQuery) WithSenses(opts ...func(*SenseQuery)) *LemmaQuery {
	query := (&SenseClient{config: lq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	lq.withSenses = query
	return lq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		WrittenForm string `json:"writtenForm,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.Lemma.Query().
//		GroupBy(lemma.FieldWrittenForm).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (lq *LemmaQuery) GroupBy(field string, fields ...string) *LemmaGroupBy {
	lq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &LemmaGroupBy{build: lq}
	grbuild.flds = &lq.ctx.Fields
	grbuild.label = lemma.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		WrittenForm string `json:"writtenForm,omitempty"`
//	}
//
//	client.Lemma.Query().
//		Select(lemma.FieldWrittenForm).
//		Scan(ctx, &v)
func (lq *LemmaQuery) Select(fields ...string) *LemmaSelect {
	lq.ctx.Fields = append(lq.ctx.Fields, fields...)
	sbuild := &LemmaSelect{LemmaQuery: lq}
	sbuild.label = lemma.Label
	sbuild.flds, sbuild.scan = &lq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a LemmaSelect configured with the given aggregations.
func (lq *LemmaQuery) Aggregate(fns ...AggregateFunc) *LemmaSelect {
	return lq.Select().Aggregate(fns...)
}

func (lq *LemmaQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range lq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, lq); err != nil {
				return err
			}
		}
	}
	for _, f := range lq.ctx.Fields {
		if !lemma.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if lq.path != nil {
		prev, err := lq.path(ctx)
		if err != nil {
			return err
		}
		lq.sql = prev
	}
	return nil
}

func (lq *LemmaQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*Lemma, error) {
	var (
		nodes       = []*Lemma{}
		_spec       = lq.querySpec()
		loadedTypes = [1]bool{
			lq.withSenses != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*Lemma).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &Lemma{config: lq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, lq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := lq.withSenses; query != nil {
		if err := lq.loadSenses(ctx, query, nodes,
			func(n *Lemma) { n.Edges.Senses = []*Sense{} },
			func(n *Lemma, e *Sense) { n.Edges.Senses = append(n.Edges.Senses, e) }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (lq *LemmaQuery) loadSenses(ctx context.Context, query *SenseQuery, nodes []*Lemma, init func(*Lemma), assign func(*Lemma, *Sense)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[string]*Lemma)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	query.withFKs = true
	query.Where(predicate.Sense(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(lemma.SensesColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.sense_lemma
		if fk == nil {
			return fmt.Errorf(`foreign-key "sense_lemma" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "sense_lemma" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (lq *LemmaQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := lq.querySpec()
	_spec.Node.Columns = lq.ctx.Fields
	if len(lq.ctx.Fields) > 0 {
		_spec.Unique = lq.ctx.Unique != nil && *lq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, lq.driver, _spec)
}

func (lq *LemmaQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(lemma.Table, lemma.Columns, sqlgraph.NewFieldSpec(lemma.FieldID, field.TypeString))
	_spec.From = lq.sql
	if unique := lq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if lq.path != nil {
		_spec.Unique = true
	}
	if fields := lq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, lemma.FieldID)
		for i := range fields {
			if fields[i] != lemma.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := lq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := lq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := lq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := lq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (lq *LemmaQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(lq.driver.Dialect())
	t1 := builder.Table(lemma.Table)
	columns := lq.ctx.Fields
	if len(columns) == 0 {
		columns = lemma.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if lq.sql != nil {
		selector = lq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if lq.ctx.Unique != nil && *lq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range lq.predicates {
		p(selector)
	}
	for _, p := range lq.order {
		p(selector)
	}
	if offset := lq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := lq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// LemmaGroupBy is the group-by builder for Lemma entities.
type LemmaGroupBy struct {
	selector
	build *LemmaQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (lgb *LemmaGroupBy) Aggregate(fns ...AggregateFunc) *LemmaGroupBy {
	lgb.fns = append(lgb.fns, fns...)
	return lgb
}

// Scan applies the selector query and scans the result into the given value.
func (lgb *LemmaGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, lgb.build.ctx, ent.OpQueryGroupBy)
	if err := lgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*LemmaQuery, *LemmaGroupBy](ctx, lgb.build, lgb, lgb.build.inters, v)
}

func (lgb *LemmaGroupBy) sqlScan(ctx context.Context, root *LemmaQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(lgb.fns))
	for _, fn := range lgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*lgb.flds)+len(lgb.fns))
		for _, f := range *lgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*lgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := lgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// LemmaSelect is the builder for selecting fields of Lemma entities.
type LemmaSelect struct {
	*LemmaQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (ls *LemmaSelect) Aggregate(fns ...AggregateFunc) *LemmaSelect {
	ls.fns = append(ls.fns, fns...)
	return ls
}

// Scan applies the selector query and scans the result into the given value.
func (ls *LemmaSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, ls.ctx, ent.OpQuerySelect)
	if err := ls.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*LemmaQuery, *LemmaSelect](ctx, ls.LemmaQuery, ls, ls.inters, v)
}

func (ls *LemmaSelect) sqlScan(ctx context.Context, root *LemmaQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(ls.fns))
	for _, fn := range ls.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*ls.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := ls.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
