// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/allof-dev/dictionary/ent/sense"
	"github.com/allof-dev/dictionary/ent/senserelation"
)

// SenseRelationCreate is the builder for creating a SenseRelation entity.
type SenseRelationCreate struct {
	config
	mutation *SenseRelationMutation
	hooks    []Hook
}

// SetRelType sets the "relType" field.
func (src *SenseRelationCreate) SetRelType(s string) *SenseRelationCreate {
	src.mutation.SetRelType(s)
	return src
}

// SetFromID sets the "from" edge to the Sense entity by ID.
func (src *SenseRelationCreate) SetFromID(id string) *SenseRelationCreate {
	src.mutation.SetFromID(id)
	return src
}

// SetFrom sets the "from" edge to the Sense entity.
func (src *SenseRelationCreate) SetFrom(s *Sense) *SenseRelationCreate {
	return src.SetFromID(s.ID)
}

// SetToID sets the "to" edge to the Sense entity by ID.
func (src *SenseRelationCreate) SetToID(id string) *SenseRelationCreate {
	src.mutation.SetToID(id)
	return src
}

// SetTo sets the "to" edge to the Sense entity.
func (src *SenseRelationCreate) SetTo(s *Sense) *SenseRelationCreate {
	return src.SetToID(s.ID)
}

// Mutation returns the SenseRelationMutation object of the builder.
func (src *SenseRelationCreate) Mutation() *SenseRelationMutation {
	return src.mutation
}

// Save creates the SenseRelation in the database.
func (src *SenseRelationCreate) Save(ctx context.Context) (*SenseRelation, error) {
	return withHooks(ctx, src.sqlSave, src.mutation, src.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (src *SenseRelationCreate) SaveX(ctx context.Context) *SenseRelation {
	v, err := src.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (src *SenseRelationCreate) Exec(ctx context.Context) error {
	_, err := src.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (src *SenseRelationCreate) ExecX(ctx context.Context) {
	if err := src.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (src *SenseRelationCreate) check() error {
	if _, ok := src.mutation.RelType(); !ok {
		return &ValidationError{Name: "relType", err: errors.New(`ent: missing required field "SenseRelation.relType"`)}
	}
	if v, ok := src.mutation.RelType(); ok {
		if err := senserelation.RelTypeValidator(v); err != nil {
			return &ValidationError{Name: "relType", err: fmt.Errorf(`ent: validator failed for field "SenseRelation.relType": %w`, err)}
		}
	}
	if len(src.mutation.FromIDs()) == 0 {
		return &ValidationError{Name: "from", err: errors.New(`ent: missing required edge "SenseRelation.from"`)}
	}
	if len(src.mutation.ToIDs()) == 0 {
		return &ValidationError{Name: "to", err: errors.New(`ent: missing required edge "SenseRelation.to"`)}
	}
	return nil
}

func (src *SenseRelationCreate) sqlSave(ctx context.Context) (*SenseRelation, error) {
	if err := src.check(); err != nil {
		return nil, err
	}
	_node, _spec := src.createSpec()
	if err := sqlgraph.CreateNode(ctx, src.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	src.mutation.id = &_node.ID
	src.mutation.done = true
	return _node, nil
}

func (src *SenseRelationCreate) createSpec() (*SenseRelation, *sqlgraph.CreateSpec) {
	var (
		_node = &SenseRelation{config: src.config}
		_spec = sqlgraph.NewCreateSpec(senserelation.Table, sqlgraph.NewFieldSpec(senserelation.FieldID, field.TypeInt))
	)
	if value, ok := src.mutation.RelType(); ok {
		_spec.SetField(senserelation.FieldRelType, field.TypeString, value)
		_node.RelType = value
	}
	if nodes := src.mutation.FromIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   senserelation.FromTable,
			Columns: []string{senserelation.FromColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(sense.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.sense_relation_from = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := src.mutation.ToIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   senserelation.ToTable,
			Columns: []string{senserelation.ToColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(sense.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.sense_relation_to = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// SenseRelationCreateBulk is the builder for creating many SenseRelation entities in bulk.
type SenseRelationCreateBulk struct {
	config
	err      error
	builders []*SenseRelationCreate
}

// Save creates the SenseRelation entities in the database.
func (srcb *SenseRelationCreateBulk) Save(ctx context.Context) ([]*SenseRelation, error) {
	if srcb.err != nil {
		return nil, srcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(srcb.builders))
	nodes := make([]*SenseRelation, len(srcb.builders))
	mutators := make([]Mutator, len(srcb.builders))
	for i := range srcb.builders {
		func(i int, root context.Context) {
			builder := srcb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*SenseRelationMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, srcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, srcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, srcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (srcb *SenseRelationCreateBulk) SaveX(ctx context.Context) []*SenseRelation {
	v, err := srcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (srcb *SenseRelationCreateBulk) Exec(ctx context.Context) error {
	_, err := srcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (srcb *SenseRelationCreateBulk) ExecX(ctx context.Context) {
	if err := srcb.Exec(ctx); err != nil {
		panic(err)
	}
}
