// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/allof-dev/dictionary/ent/definition"
	"github.com/allof-dev/dictionary/ent/synset"
	"github.com/allof-dev/dictionary/ent/synsetrelation"
)

// SynsetCreate is the builder for creating a Synset entity.
type SynsetCreate struct {
	config
	mutation *SynsetMutation
	hooks    []Hook
}

// SetPartOfSpeech sets the "partOfSpeech" field.
func (sc *SynsetCreate) SetPartOfSpeech(s string) *SynsetCreate {
	sc.mutation.SetPartOfSpeech(s)
	return sc
}

// SetID sets the "id" field.
func (sc *SynsetCreate) SetID(s string) *SynsetCreate {
	sc.mutation.SetID(s)
	return sc
}

// AddDefinitionIDs adds the "definitions" edge to the Definition entity by IDs.
func (sc *SynsetCreate) AddDefinitionIDs(ids ...int) *SynsetCreate {
	sc.mutation.AddDefinitionIDs(ids...)
	return sc
}

// AddDefinitions adds the "definitions" edges to the Definition entity.
func (sc *SynsetCreate) AddDefinitions(d ...*Definition) *SynsetCreate {
	ids := make([]int, len(d))
	for i := range d {
		ids[i] = d[i].ID
	}
	return sc.AddDefinitionIDs(ids...)
}

// AddRelFromIDs adds the "relFrom" edge to the SynsetRelation entity by IDs.
func (sc *SynsetCreate) AddRelFromIDs(ids ...int) *SynsetCreate {
	sc.mutation.AddRelFromIDs(ids...)
	return sc
}

// AddRelFrom adds the "relFrom" edges to the SynsetRelation entity.
func (sc *SynsetCreate) AddRelFrom(s ...*SynsetRelation) *SynsetCreate {
	ids := make([]int, len(s))
	for i := range s {
		ids[i] = s[i].ID
	}
	return sc.AddRelFromIDs(ids...)
}

// AddRelToIDs adds the "relTo" edge to the SynsetRelation entity by IDs.
func (sc *SynsetCreate) AddRelToIDs(ids ...int) *SynsetCreate {
	sc.mutation.AddRelToIDs(ids...)
	return sc
}

// AddRelTo adds the "relTo" edges to the SynsetRelation entity.
func (sc *SynsetCreate) AddRelTo(s ...*SynsetRelation) *SynsetCreate {
	ids := make([]int, len(s))
	for i := range s {
		ids[i] = s[i].ID
	}
	return sc.AddRelToIDs(ids...)
}

// Mutation returns the SynsetMutation object of the builder.
func (sc *SynsetCreate) Mutation() *SynsetMutation {
	return sc.mutation
}

// Save creates the Synset in the database.
func (sc *SynsetCreate) Save(ctx context.Context) (*Synset, error) {
	return withHooks(ctx, sc.sqlSave, sc.mutation, sc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (sc *SynsetCreate) SaveX(ctx context.Context) *Synset {
	v, err := sc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (sc *SynsetCreate) Exec(ctx context.Context) error {
	_, err := sc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (sc *SynsetCreate) ExecX(ctx context.Context) {
	if err := sc.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (sc *SynsetCreate) check() error {
	if _, ok := sc.mutation.PartOfSpeech(); !ok {
		return &ValidationError{Name: "partOfSpeech", err: errors.New(`ent: missing required field "Synset.partOfSpeech"`)}
	}
	if v, ok := sc.mutation.PartOfSpeech(); ok {
		if err := synset.PartOfSpeechValidator(v); err != nil {
			return &ValidationError{Name: "partOfSpeech", err: fmt.Errorf(`ent: validator failed for field "Synset.partOfSpeech": %w`, err)}
		}
	}
	if v, ok := sc.mutation.ID(); ok {
		if err := synset.IDValidator(v); err != nil {
			return &ValidationError{Name: "id", err: fmt.Errorf(`ent: validator failed for field "Synset.id": %w`, err)}
		}
	}
	return nil
}

func (sc *SynsetCreate) sqlSave(ctx context.Context) (*Synset, error) {
	if err := sc.check(); err != nil {
		return nil, err
	}
	_node, _spec := sc.createSpec()
	if err := sqlgraph.CreateNode(ctx, sc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected Synset.ID type: %T", _spec.ID.Value)
		}
	}
	sc.mutation.id = &_node.ID
	sc.mutation.done = true
	return _node, nil
}

func (sc *SynsetCreate) createSpec() (*Synset, *sqlgraph.CreateSpec) {
	var (
		_node = &Synset{config: sc.config}
		_spec = sqlgraph.NewCreateSpec(synset.Table, sqlgraph.NewFieldSpec(synset.FieldID, field.TypeString))
	)
	if id, ok := sc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := sc.mutation.PartOfSpeech(); ok {
		_spec.SetField(synset.FieldPartOfSpeech, field.TypeString, value)
		_node.PartOfSpeech = value
	}
	if nodes := sc.mutation.DefinitionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   synset.DefinitionsTable,
			Columns: []string{synset.DefinitionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(definition.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := sc.mutation.RelFromIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   synset.RelFromTable,
			Columns: []string{synset.RelFromColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(synsetrelation.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := sc.mutation.RelToIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   synset.RelToTable,
			Columns: []string{synset.RelToColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(synsetrelation.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// SynsetCreateBulk is the builder for creating many Synset entities in bulk.
type SynsetCreateBulk struct {
	config
	err      error
	builders []*SynsetCreate
}

// Save creates the Synset entities in the database.
func (scb *SynsetCreateBulk) Save(ctx context.Context) ([]*Synset, error) {
	if scb.err != nil {
		return nil, scb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(scb.builders))
	nodes := make([]*Synset, len(scb.builders))
	mutators := make([]Mutator, len(scb.builders))
	for i := range scb.builders {
		func(i int, root context.Context) {
			builder := scb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*SynsetMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, scb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, scb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, scb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (scb *SynsetCreateBulk) SaveX(ctx context.Context) []*Synset {
	v, err := scb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (scb *SynsetCreateBulk) Exec(ctx context.Context) error {
	_, err := scb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (scb *SynsetCreateBulk) ExecX(ctx context.Context) {
	if err := scb.Exec(ctx); err != nil {
		panic(err)
	}
}
