// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/allof-dev/dictionary/ent/predicate"
	"github.com/allof-dev/dictionary/ent/synset"
	"github.com/allof-dev/dictionary/ent/synsetrelation"
)

// SynsetRelationQuery is the builder for querying SynsetRelation entities.
type SynsetRelationQuery struct {
	config
	ctx        *QueryContext
	order      []synsetrelation.OrderOption
	inters     []Interceptor
	predicates []predicate.SynsetRelation
	withFrom   *SynsetQuery
	withTo     *SynsetQuery
	withFKs    bool
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the SynsetRelationQuery builder.
func (srq *SynsetRelationQuery) Where(ps ...predicate.SynsetRelation) *SynsetRelationQuery {
	srq.predicates = append(srq.predicates, ps...)
	return srq
}

// Limit the number of records to be returned by this query.
func (srq *SynsetRelationQuery) Limit(limit int) *SynsetRelationQuery {
	srq.ctx.Limit = &limit
	return srq
}

// Offset to start from.
func (srq *SynsetRelationQuery) Offset(offset int) *SynsetRelationQuery {
	srq.ctx.Offset = &offset
	return srq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (srq *SynsetRelationQuery) Unique(unique bool) *SynsetRelationQuery {
	srq.ctx.Unique = &unique
	return srq
}

// Order specifies how the records should be ordered.
func (srq *SynsetRelationQuery) Order(o ...synsetrelation.OrderOption) *SynsetRelationQuery {
	srq.order = append(srq.order, o...)
	return srq
}

// QueryFrom chains the current query on the "from" edge.
func (srq *SynsetRelationQuery) QueryFrom() *SynsetQuery {
	query := (&SynsetClient{config: srq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := srq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := srq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(synsetrelation.Table, synsetrelation.FieldID, selector),
			sqlgraph.To(synset.Table, synset.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, synsetrelation.FromTable, synsetrelation.FromColumn),
		)
		fromU = sqlgraph.SetNeighbors(srq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryTo chains the current query on the "to" edge.
func (srq *SynsetRelationQuery) QueryTo() *SynsetQuery {
	query := (&SynsetClient{config: srq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := srq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := srq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(synsetrelation.Table, synsetrelation.FieldID, selector),
			sqlgraph.To(synset.Table, synset.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, synsetrelation.ToTable, synsetrelation.ToColumn),
		)
		fromU = sqlgraph.SetNeighbors(srq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first SynsetRelation entity from the query.
// Returns a *NotFoundError when no SynsetRelation was found.
func (srq *SynsetRelationQuery) First(ctx context.Context) (*SynsetRelation, error) {
	nodes, err := srq.Limit(1).All(setContextOp(ctx, srq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{synsetrelation.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (srq *SynsetRelationQuery) FirstX(ctx context.Context) *SynsetRelation {
	node, err := srq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first SynsetRelation ID from the query.
// Returns a *NotFoundError when no SynsetRelation ID was found.
func (srq *SynsetRelationQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = srq.Limit(1).IDs(setContextOp(ctx, srq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{synsetrelation.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (srq *SynsetRelationQuery) FirstIDX(ctx context.Context) int {
	id, err := srq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single SynsetRelation entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one SynsetRelation entity is found.
// Returns a *NotFoundError when no SynsetRelation entities are found.
func (srq *SynsetRelationQuery) Only(ctx context.Context) (*SynsetRelation, error) {
	nodes, err := srq.Limit(2).All(setContextOp(ctx, srq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{synsetrelation.Label}
	default:
		return nil, &NotSingularError{synsetrelation.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (srq *SynsetRelationQuery) OnlyX(ctx context.Context) *SynsetRelation {
	node, err := srq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only SynsetRelation ID in the query.
// Returns a *NotSingularError when more than one SynsetRelation ID is found.
// Returns a *NotFoundError when no entities are found.
func (srq *SynsetRelationQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = srq.Limit(2).IDs(setContextOp(ctx, srq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{synsetrelation.Label}
	default:
		err = &NotSingularError{synsetrelation.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (srq *SynsetRelationQuery) OnlyIDX(ctx context.Context) int {
	id, err := srq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of SynsetRelations.
func (srq *SynsetRelationQuery) All(ctx context.Context) ([]*SynsetRelation, error) {
	ctx = setContextOp(ctx, srq.ctx, ent.OpQueryAll)
	if err := srq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*SynsetRelation, *SynsetRelationQuery]()
	return withInterceptors[[]*SynsetRelation](ctx, srq, qr, srq.inters)
}

// AllX is like All, but panics if an error occurs.
func (srq *SynsetRelationQuery) AllX(ctx context.Context) []*SynsetRelation {
	nodes, err := srq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of SynsetRelation IDs.
func (srq *SynsetRelationQuery) IDs(ctx context.Context) (ids []int, err error) {
	if srq.ctx.Unique == nil && srq.path != nil {
		srq.Unique(true)
	}
	ctx = setContextOp(ctx, srq.ctx, ent.OpQueryIDs)
	if err = srq.Select(synsetrelation.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (srq *SynsetRelationQuery) IDsX(ctx context.Context) []int {
	ids, err := srq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (srq *SynsetRelationQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, srq.ctx, ent.OpQueryCount)
	if err := srq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, srq, querierCount[*SynsetRelationQuery](), srq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (srq *SynsetRelationQuery) CountX(ctx context.Context) int {
	count, err := srq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (srq *SynsetRelationQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, srq.ctx, ent.OpQueryExist)
	switch _, err := srq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (srq *SynsetRelationQuery) ExistX(ctx context.Context) bool {
	exist, err := srq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the SynsetRelationQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (srq *SynsetRelationQuery) Clone() *SynsetRelationQuery {
	if srq == nil {
		return nil
	}
	return &SynsetRelationQuery{
		config:     srq.config,
		ctx:        srq.ctx.Clone(),
		order:      append([]synsetrelation.OrderOption{}, srq.order...),
		inters:     append([]Interceptor{}, srq.inters...),
		predicates: append([]predicate.SynsetRelation{}, srq.predicates...),
		withFrom:   srq.withFrom.Clone(),
		withTo:     srq.withTo.Clone(),
		// clone intermediate query.
		sql:  srq.sql.Clone(),
		path: srq.path,
	}
}

// WithFrom tells the query-builder to eager-load the nodes that are connected to
// the "from" edge. The optional arguments are used to configure the query builder of the edge.
func (srq *SynsetRelationQuery) WithFrom(opts ...func(*SynsetQuery)) *SynsetRelationQuery {
	query := (&SynsetClient{config: srq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	srq.withFrom = query
	return srq
}

// WithTo tells the query-builder to eager-load the nodes that are connected to
// the "to" edge. The optional arguments are used to configure the query builder of the edge.
func (srq *SynsetRelationQuery) WithTo(opts ...func(*SynsetQuery)) *SynsetRelationQuery {
	query := (&SynsetClient{config: srq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	srq.withTo = query
	return srq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		RelType string `json:"relType,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.SynsetRelation.Query().
//		GroupBy(synsetrelation.FieldRelType).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (srq *SynsetRelationQuery) GroupBy(field string, fields ...string) *SynsetRelationGroupBy {
	srq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &SynsetRelationGroupBy{build: srq}
	grbuild.flds = &srq.ctx.Fields
	grbuild.label = synsetrelation.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		RelType string `json:"relType,omitempty"`
//	}
//
//	client.SynsetRelation.Query().
//		Select(synsetrelation.FieldRelType).
//		Scan(ctx, &v)
func (srq *SynsetRelationQuery) Select(fields ...string) *SynsetRelationSelect {
	srq.ctx.Fields = append(srq.ctx.Fields, fields...)
	sbuild := &SynsetRelationSelect{SynsetRelationQuery: srq}
	sbuild.label = synsetrelation.Label
	sbuild.flds, sbuild.scan = &srq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a SynsetRelationSelect configured with the given aggregations.
func (srq *SynsetRelationQuery) Aggregate(fns ...AggregateFunc) *SynsetRelationSelect {
	return srq.Select().Aggregate(fns...)
}

func (srq *SynsetRelationQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range srq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, srq); err != nil {
				return err
			}
		}
	}
	for _, f := range srq.ctx.Fields {
		if !synsetrelation.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if srq.path != nil {
		prev, err := srq.path(ctx)
		if err != nil {
			return err
		}
		srq.sql = prev
	}
	return nil
}

func (srq *SynsetRelationQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*SynsetRelation, error) {
	var (
		nodes       = []*SynsetRelation{}
		withFKs     = srq.withFKs
		_spec       = srq.querySpec()
		loadedTypes = [2]bool{
			srq.withFrom != nil,
			srq.withTo != nil,
		}
	)
	if srq.withFrom != nil || srq.withTo != nil {
		withFKs = true
	}
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, synsetrelation.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*SynsetRelation).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &SynsetRelation{config: srq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, srq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := srq.withFrom; query != nil {
		if err := srq.loadFrom(ctx, query, nodes, nil,
			func(n *SynsetRelation, e *Synset) { n.Edges.From = e }); err != nil {
			return nil, err
		}
	}
	if query := srq.withTo; query != nil {
		if err := srq.loadTo(ctx, query, nodes, nil,
			func(n *SynsetRelation, e *Synset) { n.Edges.To = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (srq *SynsetRelationQuery) loadFrom(ctx context.Context, query *SynsetQuery, nodes []*SynsetRelation, init func(*SynsetRelation), assign func(*SynsetRelation, *Synset)) error {
	ids := make([]string, 0, len(nodes))
	nodeids := make(map[string][]*SynsetRelation)
	for i := range nodes {
		if nodes[i].synset_relation_from == nil {
			continue
		}
		fk := *nodes[i].synset_relation_from
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(synset.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "synset_relation_from" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (srq *SynsetRelationQuery) loadTo(ctx context.Context, query *SynsetQuery, nodes []*SynsetRelation, init func(*SynsetRelation), assign func(*SynsetRelation, *Synset)) error {
	ids := make([]string, 0, len(nodes))
	nodeids := make(map[string][]*SynsetRelation)
	for i := range nodes {
		if nodes[i].synset_relation_to == nil {
			continue
		}
		fk := *nodes[i].synset_relation_to
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(synset.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "synset_relation_to" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (srq *SynsetRelationQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := srq.querySpec()
	_spec.Node.Columns = srq.ctx.Fields
	if len(srq.ctx.Fields) > 0 {
		_spec.Unique = srq.ctx.Unique != nil && *srq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, srq.driver, _spec)
}

func (srq *SynsetRelationQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(synsetrelation.Table, synsetrelation.Columns, sqlgraph.NewFieldSpec(synsetrelation.FieldID, field.TypeInt))
	_spec.From = srq.sql
	if unique := srq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if srq.path != nil {
		_spec.Unique = true
	}
	if fields := srq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, synsetrelation.FieldID)
		for i := range fields {
			if fields[i] != synsetrelation.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := srq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := srq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := srq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := srq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (srq *SynsetRelationQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(srq.driver.Dialect())
	t1 := builder.Table(synsetrelation.Table)
	columns := srq.ctx.Fields
	if len(columns) == 0 {
		columns = synsetrelation.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if srq.sql != nil {
		selector = srq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if srq.ctx.Unique != nil && *srq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range srq.predicates {
		p(selector)
	}
	for _, p := range srq.order {
		p(selector)
	}
	if offset := srq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := srq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// SynsetRelationGroupBy is the group-by builder for SynsetRelation entities.
type SynsetRelationGroupBy struct {
	selector
	build *SynsetRelationQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (srgb *SynsetRelationGroupBy) Aggregate(fns ...AggregateFunc) *SynsetRelationGroupBy {
	srgb.fns = append(srgb.fns, fns...)
	return srgb
}

// Scan applies the selector query and scans the result into the given value.
func (srgb *SynsetRelationGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, srgb.build.ctx, ent.OpQueryGroupBy)
	if err := srgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*SynsetRelationQuery, *SynsetRelationGroupBy](ctx, srgb.build, srgb, srgb.build.inters, v)
}

func (srgb *SynsetRelationGroupBy) sqlScan(ctx context.Context, root *SynsetRelationQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(srgb.fns))
	for _, fn := range srgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*srgb.flds)+len(srgb.fns))
		for _, f := range *srgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*srgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := srgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// SynsetRelationSelect is the builder for selecting fields of SynsetRelation entities.
type SynsetRelationSelect struct {
	*SynsetRelationQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (srs *SynsetRelationSelect) Aggregate(fns ...AggregateFunc) *SynsetRelationSelect {
	srs.fns = append(srs.fns, fns...)
	return srs
}

// Scan applies the selector query and scans the result into the given value.
func (srs *SynsetRelationSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, srs.ctx, ent.OpQuerySelect)
	if err := srs.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*SynsetRelationQuery, *SynsetRelationSelect](ctx, srs.SynsetRelationQuery, srs, srs.inters, v)
}

func (srs *SynsetRelationSelect) sqlScan(ctx context.Context, root *SynsetRelationQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(srs.fns))
	for _, fn := range srs.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*srs.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := srs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
