// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/allof-dev/dictionary/ent/predicate"
	"github.com/allof-dev/dictionary/ent/synsetrelation"
)

// SynsetRelationDelete is the builder for deleting a SynsetRelation entity.
type SynsetRelationDelete struct {
	config
	hooks    []Hook
	mutation *SynsetRelationMutation
}

// Where appends a list predicates to the SynsetRelationDelete builder.
func (srd *SynsetRelationDelete) Where(ps ...predicate.SynsetRelation) *SynsetRelationDelete {
	srd.mutation.Where(ps...)
	return srd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (srd *SynsetRelationDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, srd.sqlExec, srd.mutation, srd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (srd *SynsetRelationDelete) ExecX(ctx context.Context) int {
	n, err := srd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (srd *SynsetRelationDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(synsetrelation.Table, sqlgraph.NewFieldSpec(synsetrelation.FieldID, field.TypeInt))
	if ps := srd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, srd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	srd.mutation.done = true
	return affected, err
}

// SynsetRelationDeleteOne is the builder for deleting a single SynsetRelation entity.
type SynsetRelationDeleteOne struct {
	srd *SynsetRelationDelete
}

// Where appends a list predicates to the SynsetRelationDelete builder.
func (srdo *SynsetRelationDeleteOne) Where(ps ...predicate.SynsetRelation) *SynsetRelationDeleteOne {
	srdo.srd.mutation.Where(ps...)
	return srdo
}

// Exec executes the deletion query.
func (srdo *SynsetRelationDeleteOne) Exec(ctx context.Context) error {
	n, err := srdo.srd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{synsetrelation.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (srdo *SynsetRelationDeleteOne) ExecX(ctx context.Context) {
	if err := srdo.Exec(ctx); err != nil {
		panic(err)
	}
}
