// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/allof-dev/dictionary/ent/definition"
	"github.com/allof-dev/dictionary/ent/predicate"
	"github.com/allof-dev/dictionary/ent/synset"
	"github.com/allof-dev/dictionary/ent/synsetrelation"
)

// SynsetQuery is the builder for querying Synset entities.
type SynsetQuery struct {
	config
	ctx             *QueryContext
	order           []synset.OrderOption
	inters          []Interceptor
	predicates      []predicate.Synset
	withDefinitions *DefinitionQuery
	withRelFrom     *SynsetRelationQuery
	withRelTo       *SynsetRelationQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the SynsetQuery builder.
func (sq *SynsetQuery) Where(ps ...predicate.Synset) *SynsetQuery {
	sq.predicates = append(sq.predicates, ps...)
	return sq
}

// Limit the number of records to be returned by this query.
func (sq *SynsetQuery) Limit(limit int) *SynsetQuery {
	sq.ctx.Limit = &limit
	return sq
}

// Offset to start from.
func (sq *SynsetQuery) Offset(offset int) *SynsetQuery {
	sq.ctx.Offset = &offset
	return sq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (sq *SynsetQuery) Unique(unique bool) *SynsetQuery {
	sq.ctx.Unique = &unique
	return sq
}

// Order specifies how the records should be ordered.
func (sq *SynsetQuery) Order(o ...synset.OrderOption) *SynsetQuery {
	sq.order = append(sq.order, o...)
	return sq
}

// QueryDefinitions chains the current query on the "definitions" edge.
func (sq *SynsetQuery) QueryDefinitions() *DefinitionQuery {
	query := (&DefinitionClient{config: sq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := sq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := sq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(synset.Table, synset.FieldID, selector),
			sqlgraph.To(definition.Table, definition.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, synset.DefinitionsTable, synset.DefinitionsColumn),
		)
		fromU = sqlgraph.SetNeighbors(sq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryRelFrom chains the current query on the "relFrom" edge.
func (sq *SynsetQuery) QueryRelFrom() *SynsetRelationQuery {
	query := (&SynsetRelationClient{config: sq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := sq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := sq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(synset.Table, synset.FieldID, selector),
			sqlgraph.To(synsetrelation.Table, synsetrelation.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, true, synset.RelFromTable, synset.RelFromColumn),
		)
		fromU = sqlgraph.SetNeighbors(sq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryRelTo chains the current query on the "relTo" edge.
func (sq *SynsetQuery) QueryRelTo() *SynsetRelationQuery {
	query := (&SynsetRelationClient{config: sq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := sq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := sq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(synset.Table, synset.FieldID, selector),
			sqlgraph.To(synsetrelation.Table, synsetrelation.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, true, synset.RelToTable, synset.RelToColumn),
		)
		fromU = sqlgraph.SetNeighbors(sq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first Synset entity from the query.
// Returns a *NotFoundError when no Synset was found.
func (sq *SynsetQuery) First(ctx context.Context) (*Synset, error) {
	nodes, err := sq.Limit(1).All(setContextOp(ctx, sq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{synset.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (sq *SynsetQuery) FirstX(ctx context.Context) *Synset {
	node, err := sq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first Synset ID from the query.
// Returns a *NotFoundError when no Synset ID was found.
func (sq *SynsetQuery) FirstID(ctx context.Context) (id string, err error) {
	var ids []string
	if ids, err = sq.Limit(1).IDs(setContextOp(ctx, sq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{synset.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (sq *SynsetQuery) FirstIDX(ctx context.Context) string {
	id, err := sq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single Synset entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one Synset entity is found.
// Returns a *NotFoundError when no Synset entities are found.
func (sq *SynsetQuery) Only(ctx context.Context) (*Synset, error) {
	nodes, err := sq.Limit(2).All(setContextOp(ctx, sq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{synset.Label}
	default:
		return nil, &NotSingularError{synset.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (sq *SynsetQuery) OnlyX(ctx context.Context) *Synset {
	node, err := sq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only Synset ID in the query.
// Returns a *NotSingularError when more than one Synset ID is found.
// Returns a *NotFoundError when no entities are found.
func (sq *SynsetQuery) OnlyID(ctx context.Context) (id string, err error) {
	var ids []string
	if ids, err = sq.Limit(2).IDs(setContextOp(ctx, sq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{synset.Label}
	default:
		err = &NotSingularError{synset.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (sq *SynsetQuery) OnlyIDX(ctx context.Context) string {
	id, err := sq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of Synsets.
func (sq *SynsetQuery) All(ctx context.Context) ([]*Synset, error) {
	ctx = setContextOp(ctx, sq.ctx, ent.OpQueryAll)
	if err := sq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*Synset, *SynsetQuery]()
	return withInterceptors[[]*Synset](ctx, sq, qr, sq.inters)
}

// AllX is like All, but panics if an error occurs.
func (sq *SynsetQuery) AllX(ctx context.Context) []*Synset {
	nodes, err := sq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of Synset IDs.
func (sq *SynsetQuery) IDs(ctx context.Context) (ids []string, err error) {
	if sq.ctx.Unique == nil && sq.path != nil {
		sq.Unique(true)
	}
	ctx = setContextOp(ctx, sq.ctx, ent.OpQueryIDs)
	if err = sq.Select(synset.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (sq *SynsetQuery) IDsX(ctx context.Context) []string {
	ids, err := sq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (sq *SynsetQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, sq.ctx, ent.OpQueryCount)
	if err := sq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, sq, querierCount[*SynsetQuery](), sq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (sq *SynsetQuery) CountX(ctx context.Context) int {
	count, err := sq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (sq *SynsetQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, sq.ctx, ent.OpQueryExist)
	switch _, err := sq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (sq *SynsetQuery) ExistX(ctx context.Context) bool {
	exist, err := sq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the SynsetQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (sq *SynsetQuery) Clone() *SynsetQuery {
	if sq == nil {
		return nil
	}
	return &SynsetQuery{
		config:          sq.config,
		ctx:             sq.ctx.Clone(),
		order:           append([]synset.OrderOption{}, sq.order...),
		inters:          append([]Interceptor{}, sq.inters...),
		predicates:      append([]predicate.Synset{}, sq.predicates...),
		withDefinitions: sq.withDefinitions.Clone(),
		withRelFrom:     sq.withRelFrom.Clone(),
		withRelTo:       sq.withRelTo.Clone(),
		// clone intermediate query.
		sql:  sq.sql.Clone(),
		path: sq.path,
	}
}

// WithDefinitions tells the query-builder to eager-load the nodes that are connected to
// the "definitions" edge. The optional arguments are used to configure the query builder of the edge.
func (sq *SynsetQuery) WithDefinitions(opts ...func(*DefinitionQuery)) *SynsetQuery {
	query := (&DefinitionClient{config: sq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	sq.withDefinitions = query
	return sq
}

// WithRelFrom tells the query-builder to eager-load the nodes that are connected to
// the "relFrom" edge. The optional arguments are used to configure the query builder of the edge.
func (sq *SynsetQuery) WithRelFrom(opts ...func(*SynsetRelationQuery)) *SynsetQuery {
	query := (&SynsetRelationClient{config: sq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	sq.withRelFrom = query
	return sq
}

// WithRelTo tells the query-builder to eager-load the nodes that are connected to
// the "relTo" edge. The optional arguments are used to configure the query builder of the edge.
func (sq *SynsetQuery) WithRelTo(opts ...func(*SynsetRelationQuery)) *SynsetQuery {
	query := (&SynsetRelationClient{config: sq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	sq.withRelTo = query
	return sq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		PartOfSpeech string `json:"partOfSpeech,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.Synset.Query().
//		GroupBy(synset.FieldPartOfSpeech).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (sq *SynsetQuery) GroupBy(field string, fields ...string) *SynsetGroupBy {
	sq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &SynsetGroupBy{build: sq}
	grbuild.flds = &sq.ctx.Fields
	grbuild.label = synset.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		PartOfSpeech string `json:"partOfSpeech,omitempty"`
//	}
//
//	client.Synset.Query().
//		Select(synset.FieldPartOfSpeech).
//		Scan(ctx, &v)
func (sq *SynsetQuery) Select(fields ...string) *SynsetSelect {
	sq.ctx.Fields = append(sq.ctx.Fields, fields...)
	sbuild := &SynsetSelect{SynsetQuery: sq}
	sbuild.label = synset.Label
	sbuild.flds, sbuild.scan = &sq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a SynsetSelect configured with the given aggregations.
func (sq *SynsetQuery) Aggregate(fns ...AggregateFunc) *SynsetSelect {
	return sq.Select().Aggregate(fns...)
}

func (sq *SynsetQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range sq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, sq); err != nil {
				return err
			}
		}
	}
	for _, f := range sq.ctx.Fields {
		if !synset.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if sq.path != nil {
		prev, err := sq.path(ctx)
		if err != nil {
			return err
		}
		sq.sql = prev
	}
	return nil
}

func (sq *SynsetQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*Synset, error) {
	var (
		nodes       = []*Synset{}
		_spec       = sq.querySpec()
		loadedTypes = [3]bool{
			sq.withDefinitions != nil,
			sq.withRelFrom != nil,
			sq.withRelTo != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*Synset).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &Synset{config: sq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, sq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := sq.withDefinitions; query != nil {
		if err := sq.loadDefinitions(ctx, query, nodes,
			func(n *Synset) { n.Edges.Definitions = []*Definition{} },
			func(n *Synset, e *Definition) { n.Edges.Definitions = append(n.Edges.Definitions, e) }); err != nil {
			return nil, err
		}
	}
	if query := sq.withRelFrom; query != nil {
		if err := sq.loadRelFrom(ctx, query, nodes,
			func(n *Synset) { n.Edges.RelFrom = []*SynsetRelation{} },
			func(n *Synset, e *SynsetRelation) { n.Edges.RelFrom = append(n.Edges.RelFrom, e) }); err != nil {
			return nil, err
		}
	}
	if query := sq.withRelTo; query != nil {
		if err := sq.loadRelTo(ctx, query, nodes,
			func(n *Synset) { n.Edges.RelTo = []*SynsetRelation{} },
			func(n *Synset, e *SynsetRelation) { n.Edges.RelTo = append(n.Edges.RelTo, e) }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (sq *SynsetQuery) loadDefinitions(ctx context.Context, query *DefinitionQuery, nodes []*Synset, init func(*Synset), assign func(*Synset, *Definition)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[string]*Synset)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	query.withFKs = true
	query.Where(predicate.Definition(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(synset.DefinitionsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.synset_definitions
		if fk == nil {
			return fmt.Errorf(`foreign-key "synset_definitions" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "synset_definitions" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (sq *SynsetQuery) loadRelFrom(ctx context.Context, query *SynsetRelationQuery, nodes []*Synset, init func(*Synset), assign func(*Synset, *SynsetRelation)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[string]*Synset)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	query.withFKs = true
	query.Where(predicate.SynsetRelation(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(synset.RelFromColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.synset_relation_to
		if fk == nil {
			return fmt.Errorf(`foreign-key "synset_relation_to" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "synset_relation_to" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (sq *SynsetQuery) loadRelTo(ctx context.Context, query *SynsetRelationQuery, nodes []*Synset, init func(*Synset), assign func(*Synset, *SynsetRelation)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[string]*Synset)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	query.withFKs = true
	query.Where(predicate.SynsetRelation(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(synset.RelToColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.synset_relation_from
		if fk == nil {
			return fmt.Errorf(`foreign-key "synset_relation_from" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "synset_relation_from" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (sq *SynsetQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := sq.querySpec()
	_spec.Node.Columns = sq.ctx.Fields
	if len(sq.ctx.Fields) > 0 {
		_spec.Unique = sq.ctx.Unique != nil && *sq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, sq.driver, _spec)
}

func (sq *SynsetQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(synset.Table, synset.Columns, sqlgraph.NewFieldSpec(synset.FieldID, field.TypeString))
	_spec.From = sq.sql
	if unique := sq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if sq.path != nil {
		_spec.Unique = true
	}
	if fields := sq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, synset.FieldID)
		for i := range fields {
			if fields[i] != synset.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := sq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := sq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := sq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := sq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (sq *SynsetQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(sq.driver.Dialect())
	t1 := builder.Table(synset.Table)
	columns := sq.ctx.Fields
	if len(columns) == 0 {
		columns = synset.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if sq.sql != nil {
		selector = sq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if sq.ctx.Unique != nil && *sq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range sq.predicates {
		p(selector)
	}
	for _, p := range sq.order {
		p(selector)
	}
	if offset := sq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := sq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// SynsetGroupBy is the group-by builder for Synset entities.
type SynsetGroupBy struct {
	selector
	build *SynsetQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (sgb *SynsetGroupBy) Aggregate(fns ...AggregateFunc) *SynsetGroupBy {
	sgb.fns = append(sgb.fns, fns...)
	return sgb
}

// Scan applies the selector query and scans the result into the given value.
func (sgb *SynsetGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, sgb.build.ctx, ent.OpQueryGroupBy)
	if err := sgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*SynsetQuery, *SynsetGroupBy](ctx, sgb.build, sgb, sgb.build.inters, v)
}

func (sgb *SynsetGroupBy) sqlScan(ctx context.Context, root *SynsetQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(sgb.fns))
	for _, fn := range sgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*sgb.flds)+len(sgb.fns))
		for _, f := range *sgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*sgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := sgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// SynsetSelect is the builder for selecting fields of Synset entities.
type SynsetSelect struct {
	*SynsetQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (ss *SynsetSelect) Aggregate(fns ...AggregateFunc) *SynsetSelect {
	ss.fns = append(ss.fns, fns...)
	return ss
}

// Scan applies the selector query and scans the result into the given value.
func (ss *SynsetSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, ss.ctx, ent.OpQuerySelect)
	if err := ss.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*SynsetQuery, *SynsetSelect](ctx, ss.SynsetQuery, ss, ss.inters, v)
}

func (ss *SynsetSelect) sqlScan(ctx context.Context, root *SynsetQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(ss.fns))
	for _, fn := range ss.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*ss.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := ss.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
