// Code generated by ent, DO NOT EDIT.

package definition

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the definition type in the database.
	Label = "definition"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldText holds the string denoting the text field in the database.
	FieldText = "text"
	// EdgeSynset holds the string denoting the synset edge name in mutations.
	EdgeSynset = "synset"
	// Table holds the table name of the definition in the database.
	Table = "definitions"
	// SynsetTable is the table that holds the synset relation/edge.
	SynsetTable = "definitions"
	// SynsetInverseTable is the table name for the Synset entity.
	// It exists in this package in order to avoid circular dependency with the "synset" package.
	SynsetInverseTable = "synsets"
	// SynsetColumn is the table column denoting the synset relation/edge.
	SynsetColumn = "synset_definitions"
)

// Columns holds all SQL columns for definition fields.
var Columns = []string{
	FieldID,
	FieldText,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "definitions"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"synset_definitions",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

var (
	// TextValidator is a validator for the "text" field. It is called by the builders before save.
	TextValidator func(string) error
)

// OrderOption defines the ordering options for the Definition queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByText orders the results by the text field.
func ByText(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldText, opts...).ToFunc()
}

// BySynsetField orders the results by synset field.
func BySynsetField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newSynsetStep(), sql.OrderByField(field, opts...))
	}
}
func newSynsetStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(SynsetInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, SynsetTable, SynsetColumn),
	)
}
