// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Definition is the predicate function for definition builders.
type Definition func(*sql.Selector)

// Lemma is the predicate function for lemma builders.
type Lemma func(*sql.Selector)

// Sense is the predicate function for sense builders.
type Sense func(*sql.Selector)

// SenseRelation is the predicate function for senserelation builders.
type SenseRelation func(*sql.Selector)

// Synset is the predicate function for synset builders.
type Synset func(*sql.Selector)

// SynsetRelation is the predicate function for synsetrelation builders.
type SynsetRelation func(*sql.Selector)
